### ISSUE TITLE
Copyright infringement notice: Willful voilation of the AGPL license

### ISSUE THREAD

**Issue by Alluneve** [jawslouis/MakePlacePlugin#27]
hello @jawslouis,

you're playing a rather dangerous game there my friend.
you are [openly stating that you're actively breaking the AGPL copyright license and are actively breaking copyright law.](https://github.com/jawslouis/MakePlacePlugin/issues/25#issuecomment-1851228718)

if no one else does it, I will take the time and effort to write up a full copyright claim that MakePlacePlugin and the private repository version of MakePlacePlugin are actively breaking the AGPL with the following resource.

https://docs.github.com/en/site-policy/content-removal-policies/guide-to-submitting-a-dmca-takedown-notice

you have 48 hours to publicise your code,
With wonderful regards,

someone who cares about the principles of copyleft

edit: this will be executed on 2023, December 14th, 18:15 UTC

**Comment by Alluneve** [comment]
Painful it may be to inform readers of this issue on this page, following the [Senior Courts Act 1981](https://www.legislation.gov.uk/ukpga/1981/54/section/31) I don't have enough legal standing to be a significant interest on behalf and as part of [GoatCorp](https://github.com/goatcorp).

I, however, highly encourage the court of public opinion to rile up for the principles of copyleft, and everything the [free software foundation](https://www.fsf.org) stands for.

I also specifically want to address [Goaaats](https://github.com/goaaats) as the significant interest of GoatCorp to utilise the copyrights on Dalamud to file a complaint at the guide mentioned above by filling the form to get this abuse of copyleft set straight.

**Comment by Spookerton** [comment]
Disinterested driveby-

It's worth noting that this is not a matter of unlicensed distribution but an allegation of license violation, and so a DMCA is not a valid option. In fact, a bad faith DMCA notice can have account or legal consequences for the submitting party. The correct route for resolution is shown at https://www.gnu.org/licenses/gpl-violation.en.html and, due to `"only the copyright holders are legally empowered to act against violations"` being true in pretty much all countries, it would be the responsibility of @goatcorp to go ahead with action, not some random users.

~~And speaking of @goatcorp - the author of #26 and related have jumped the gun a little. @jawslouis does not distribute MakePlace, goatcorp do after it has been distributed to them by jawslouis. The license relationship is between goatcorp and the users, not jawslouis and the users. ***Even if*** the AGPLv3 applies to Dalamud plugins at their origin (arguable, as all plugin authors make use of is an API) jawslouis has no obligation to publish the source code for MakePlace to the users - instead goatcorp do, and this particular mess should be in their lap instead.~~

**Comment by NotNite** [comment]
Your last paragraph is incorrect. MakePlace does not exist on the official repository and is not distributed by goatcorp (through XLWebServices); it is distributed through GitHub Releases and downloaded by the Dalamud plugin framework through a "custom repository" (URL to a JSON file).

**Comment by Spookerton** [comment]
Oh, yep. That's fair. Assumed this was one of the managed ones since it's blowing up elsewhere. Distribution direction dead.

**Comment by reiichi001** [comment]
> Oh, yep. That's fair. Assumed this was one of the managed ones since it's blowing up elsewhere. Distribution direction dead.

Main repo plugins require source to be available, as our build system pulls from git to build it. We don't accept binaries on the main repo anymore. That's why https://github.com/goatcorp/DalamudPluginsD17 is really just a collection of git hashes and repositories, along with the needed glue to confirm maintainer status / send it to the build system. It is possible to ship secrets in the build system as needed, but that's a different topic from this issue altogether. 

-- one of the people who approves main repo builds and merges

**Comment by MTobisch** [comment]
I feel like this is kind of an interesting situation legally. It basically boils down to whether the use of api calls and various helper classes meant for plugins to communicate with the main Dalamud framework constitutes sufficient use of code protected under the AGPLv3 license that the license also applies to the plugin - even though all the non-boilerplate code of the plugin is original work. Gut feeling says yes, but I'm not knowledgeable on the legal precendent.

**Comment by Spookerton** [comment]
If it were LGPL one could build a dalamud library and call to it at runtime to keep plugin code closed source, but full GPL and AGPL are intentionally virulent. As for sufficient use - use at all is sufficient. 🙃

**Comment by jawslouis** [comment]
Plugin is open source again and source code is updated.
